### ISSUE TITLE
Customise Supported Symbols

### ISSUE THREAD

**Issue by aaron-moore-ST** [HamedFathi/PasswordMeter#1]
Our use-case for implementing a password meter only has support for a limited subset of symbols (eg. not emoji). This leads to the meter recommending as strong passwords that will actually be rejected by our validation. We'd like to be able to specify our own list of symbols which would be used instead of "not letter/number" when testing required values and calculating a score.

An example of what we'd like to do:
```
new PasswordMeter({"symbols": "!"}).getResponse("@") == {"score": -1, "status": "needs requirement(s)"}
```

One possible way this could be implemented would be to make the following changes:
PasswordMeter - add a property with a regex to identify symbols
```
this.symbolsRegex = requirements.symbols || "[^a-zA-Z0-9]";
```

isSymbol - change this to test against the new regular expression:
```
pattern = new RegExp("^" + this.symbolsRegex + "$");
return pattern.test(text);
```

getRequirementScore - change this to use the new regular expression for symbolsCount:
```
var symbolsCount = (text.match(new RegExp(this.symbols, "g")) || []).length;
```

**Comment by HamedFathi** [comment]
@aaron-moore-ST 

Sure, I will check it

**Comment by HamedFathi** [comment]
In version 3.3: Everything except letters (a-z and A-Z) and numbers (0-9) are considered symbols so the symbols are not defined in advance.
