### ISSUE TITLE
What does "percent" mean in getResult() ?

### ISSUE THREAD

**Issue by rexfng** [HamedFathi/PasswordMeter#2]
Hi,

Thanks for building this. Pretty neat stuff. Just wonder if you can shed some insight as what "Percent" means in the results

**Comment by HamedFathi** [comment]
You define a set of rules for a strong password, then you enter a value as a password for the program. The percentage represents the amount of power and implementation of the rules you are considering.

See the sample [here](https://aurelia-toolbelt.github.io/#/bootstrap/password)
