### ISSUE TITLE
Exclude doesn't work for uppercase and lowercase

### ISSUE THREAD

**Issue by lazars14** [HamedFathi/PasswordMeter#3]
Hi,

I've tried to use exclude with some a value 'test'. When I enter the password 'Test', it doesn't detect the excluded value. Can you make a fix so that exclusion works for both lowercase and uppercase input values (ex. 'tEst')?

**Comment by HamedFathi** [comment]
@lazars14 

Thanks, I will check it soon

**Comment by HamedFathi** [comment]
@lazars14 

Sorry for the delay, I added this feature to version 3.2.
