### ISSUE TITLE
uniqueLettersMinLength - Require a certain amount of different letters in the password

### ISSUE THREAD

**Issue by martin-braun** [HamedFathi/PasswordMeter#4]
Hi, this is a great component. However, I think it would profit from a `uniqueLettersMinLength` option, so that a password like `aZ&4aZ&4` results in a score of 0, when `uniqueLettersMinLength` is set to `5`.

**Comment by HamedFathi** [comment]
Done!, check the latest version

**Comment by martin-braun** [comment]
> Done!, check the latest version

Thanks, I've checked it. The field should be optional, I made a pull request to fix this (#5).
